//! Assemblers: Keystone (optional) and vendored FASM fallback.

use std::env;
use std::fs;
use std::io::{self, Read, Write};
use std::path::PathBuf;
use std::process::Command;

use crate::arch::Bits;
use crate::util::{self, BoxError};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum Backend {
    Keystone,
    Fasm,
}

impl Backend {
    fn parse(s: &str) -> Result<Self, BoxError> {
        match s.to_ascii_lowercase().as_str() {
            "keystone" | "ks" => Ok(Self::Keystone),
            "fasm" => Ok(Self::Fasm),
            other => Err(format!("invalid --backend '{other}' (keystone|fasm)").into()),
        }
    }

    fn default_available() -> Result<Self, BoxError> {
        if cfg!(feature = "keystone") {
            Ok(Self::Keystone)
        } else {
            Ok(Self::Fasm)
        }
    }
}

pub fn cmd(args_in: &[String]) -> Result<(), BoxError> {
    let mut args = args_in.to_vec();
    let backend = match util::take_opt(&mut args, &["--backend"])? {
        Some(s) => Backend::parse(&s)?,
        None => Backend::default_available()?,
    };
    let bits = match util::take_opt(&mut args, &["--bits"])? {
        Some(s) => Bits::parse(&s)?,
        None => Bits::default(),
    };
    let addr = util::take_opt(&mut args, &["--addr"])?
        .map(|s| util::parse_u64_auto(&s))
        .transpose()?
        .unwrap_or(0);
    let out = util::take_opt(&mut args, &["--out", "-o"])?;
    let insn = util::take_opt(&mut args, &["--insn"])?;

    let source = if let Some(i) = insn {
        i
    } else {
        let path = util::require_path(&args, "asm file (or '-' for stdin / use --insn)")?;
        if path == "-" {
            let mut buf = String::new();
            io::stdin().read_to_string(&mut buf)?;
            buf
        } else {
            fs::read_to_string(&path)?
        }
    };

    let bytes = match backend {
        Backend::Keystone => asm_keystone(&source, bits, addr)?,
        Backend::Fasm => asm_fasm(&source, bits)?,
    };

    if let Some(path) = out {
        fs::write(&path, &bytes)?;
        eprintln!("wrote {} bytes → {path}", bytes.len());
    } else {
        // Hex dump to stdout (binary-safe for pipes: use --out for raw).
        for (i, chunk) in bytes.chunks(16).enumerate() {
            let hex: String = chunk
                .iter()
                .map(|b| format!("{b:02X}"))
                .collect::<Vec<_>>()
                .join(" ");
            println!("{:08X}: {}", i * 16, hex);
        }
        eprintln!("({} bytes; pass --out FILE for raw)", bytes.len());
    }
    Ok(())
}

#[cfg(feature = "keystone")]
fn asm_keystone(source: &str, bits: Bits, addr: u64) -> Result<Vec<u8>, BoxError> {
    use keystone_engine::{Arch, Keystone, Mode, OptionType, OptionValue};

    let mode = match bits {
        Bits::B16 => Mode::MODE_16,
        Bits::B32 => Mode::MODE_32,
        Bits::B64 => Mode::MODE_64,
    };
    let ks = Keystone::new(Arch::X86, mode).map_err(|e| format!("keystone init: {e:?}"))?;
    ks.option(OptionType::SYNTAX, OptionValue::SYNTAX_INTEL)
        .map_err(|e| format!("keystone syntax: {e:?}"))?;
    let result = ks
        .asm(source.to_string(), addr)
        .map_err(|e| format!("keystone asm: {e:?}"))?;
    Ok(result.bytes)
}

#[cfg(not(feature = "keystone"))]
fn asm_keystone(_source: &str, _bits: Bits, _addr: u64) -> Result<Vec<u8>, BoxError> {
    Err(
        "keystone backend not compiled in (cargo build -F keystone; needs cmake + C++). \
         Use --backend fasm, or install cmake and rebuild."
            .into(),
    )
}

/// Assemble via vendored FASM: wrap the snippet in a tiny flat binary template.
fn asm_fasm(source: &str, bits: Bits) -> Result<Vec<u8>, BoxError> {
    if bits == Bits::B64 {
        return Err("FASM backend in binutil only supports 16/32-bit (Kolibri default)".into());
    }
    let fasm = find_fasm()?;
    let tmp_dir = env::temp_dir().join(format!("binutil-fasm-{}", std::process::id()));
    fs::create_dir_all(&tmp_dir)?;
    let asm_path = tmp_dir.join("in.asm");
    let bin_path = tmp_dir.join("out.bin");

    let use16 = if bits == Bits::B16 { "use16" } else { "use32" };
    // Strip optional leading `use16`/`use32` from caller text to avoid duplicates.
    let body = strip_use_directive(source);
    let wrapped = format!(
        "; generated by binutil\n\
         format binary\n\
         {use16}\n\
         {body}\n"
    );
    fs::write(&asm_path, wrapped)?;

    let status = Command::new(&fasm)
        .arg(&asm_path)
        .arg(&bin_path)
        .status()
        .map_err(|e| format!("failed to spawn FASM ({}): {e}", fasm.display()))?;
    if !status.success() {
        let _ = fs::remove_dir_all(&tmp_dir);
        return Err(format!("FASM exited with {status}").into());
    }
    let bytes = fs::read(&bin_path)?;
    let _ = fs::remove_dir_all(&tmp_dir);
    Ok(bytes)
}

fn strip_use_directive(source: &str) -> String {
    let mut lines = source.lines().peekable();
    while let Some(line) = lines.peek() {
        let t = line.trim().to_ascii_lowercase();
        if t.is_empty() || t.starts_with(';') {
            lines.next();
            continue;
        }
        if t == "use16" || t == "use32" || t == "use64" {
            lines.next();
        }
        break;
    }
    lines.collect::<Vec<_>>().join("\n")
}

fn find_fasm() -> Result<PathBuf, BoxError> {
    if let Ok(p) = env::var("FASM") {
        let pb = PathBuf::from(p);
        if pb.is_file() {
            return Ok(pb);
        }
    }
    // Walk up from CWD and from this executable looking for tools/fasm/FASM.EXE
    let mut candidates = Vec::new();
    if let Ok(cwd) = env::current_dir() {
        candidates.push(cwd.clone());
        if let Some(p) = cwd.ancestors().nth(1) {
            candidates.push(p.to_path_buf());
        }
        for a in cwd.ancestors().take(6) {
            candidates.push(a.to_path_buf());
        }
    }
    if let Ok(exe) = env::current_exe() {
        if let Some(dir) = exe.parent() {
            for a in dir.ancestors().take(8) {
                candidates.push(a.to_path_buf());
            }
        }
    }
    for root in candidates {
        for rel in [
            "tools/fasm/FASM.EXE",
            "tools/fasm/fasm.exe",
            "tools/fasm/fasm",
            "FASM.EXE",
            "fasm",
        ] {
            let p = root.join(rel);
            if p.is_file() {
                return Ok(p);
            }
        }
    }
    // Last resort: PATH
    Ok(PathBuf::from(if cfg!(windows) { "FASM.EXE" } else { "fasm" }))
}

#[allow(dead_code)]
fn write_stdout_raw(bytes: &[u8]) -> Result<(), BoxError> {
    let mut out = io::stdout().lock();
    out.write_all(bytes)?;
    Ok(())
}
